### ISSUE TITLE
New `Kazan.Models` Module Orgnanization for `ApiMachinery`

### ISSUE THREAD

**Issue by mayppong** [obmarg/kazan#26]
So I'm working with `kazan`'s master branch which has the new module organization changes. Based on the [comment in the commit](https://github.com/obmarg/kazan/commit/8e35efed74d6e88ad828c91e9a37da4f1a45c0f4#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR22), I assume that the ObjectMeta would still be under the same location as it is [now](https://hexdocs.pm/kazan/Kazan.Models.ApiMachinery.Apis.Meta.V1.ObjectMeta.html).

However, when I alias `Kazan.Models.ApiMachinery.Apis.Meta.V1.ObjectMeta`, I get this error message:
```
== Compilation error in file lib/ephemeral/kube.ex ==
** (CompileError) lib/ephemeral/kube.ex:28: Kazan.Models.ApiMachinery.Apis.Meta.V1.ObjectMeta.__struct__/1 is undefined, cannot expand struct Kazan.Models.ApiMachinery.Apis.Meta.V1.ObjectMeta
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.@/1
    lib/ephemeral/kube.ex:28: Ephemeral.Kube (module)
```

I'm not sure where it is now in `master` branch so it would be nice if there was a little more description for models that are staying in the same module structure or if they changed in some other way unlike the other API models.

Thank you,

**Comment by obmarg** [comment]
Hey @mayppong - thanks for raising this.

I need to investigate when I get a bit more time, but this might have actually been a mistake when re-organising the various modules.  For now you can find the `ApiMachinery` stuff under `Kazan.Models.Apimachinery` (note the small m `ApiMachinery` `Apimachinery`).  So `ObjectMeta` is under `Kazan.Models.Apimachinery.Meta.V1.ObjectMeta`.

I suspect I'll end up changing things back to the old path in an hour or two, I just want to make sure of a few things first.

**Comment by obmarg** [comment]
Actually, I think this was done as part of #13.  The k8s specs don't expose names in a way that's  easy to automatically convert to CamelCase.  Prior to #13 we had a handful of places where we'd manually converted, ApiMachinery being one of these places.  However, since we didn't do it _everywhere_ it seemed like it'd be more consistent to keep all modules with just the first letter uppercased, the rest lower case.

However, I'm not entirely sure I want to keep things like this.  Maybe ApiMachinery should be one of the exceptions.   What do you think @mayppong ?

At the very least I need to document this change in the changelog - obviously haven't done a good job of that yet.

**Comment by mayppong** [comment]
I don't think it's a big deal to use `Apimachinery`. I prefer consistency and predictability over looking nice.
